project_id = "referiate-v0"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[auth]
enabled = true
site_url = "https://nullcost.xyz"
additional_redirect_urls = ["https://nullcost.xyz/auth", "https://www.nullcost.xyz/auth", "http://localhost:3000/auth", "http://127.0.0.1:3000/auth", "http://localhost:3000", "http://127.0.0.1:3000"]

[auth.email]
enable_signup = true
enable_confirmations = true
max_frequency = "1m0s"
otp_length = 8

[auth.mfa.totp]
enroll_enabled = true
verify_enabled = true
