create extension if not exists pgcrypto;

create table if not exists public.providers (
    id uuid primary key default gen_random_uuid(),
    slug text not null unique,
    name text not null,
    category text,
    subcategory text,
    website text,
    use_case text,
    self_serve text default 'unknown' check (self_serve in ('yes', 'no', 'unknown', 'mixed')),
    affiliate_status text default 'unknown' check (affiliate_status in ('available', 'not_found_quick_check', 'unknown')),
    referral_status text default 'unknown' check (referral_status in ('available', 'not_found_quick_check', 'unknown')),
    other_programs text,
    program_notes text,
    source_url text,
    research_status text default 'seed_only' check (research_status in ('verified_program', 'quick_official_check', 'seed_only')),
    last_verified date,
    pricing_url text,
    docs_url text,
    signup_url text,
    pricing_model text check (pricing_model in ('usage_based', 'seat_based', 'tiered', 'contact_sales')),
    starting_price text,
    free_tier text default 'unknown' check (free_tier in ('yes', 'no', 'unknown')),
    free_trial text default 'unknown' check (free_trial in ('yes', 'no', 'unknown')),
    contact_sales_only text default 'unknown' check (contact_sales_only in ('yes', 'no', 'unknown')),
    deployment_model text check (deployment_model in ('hosted', 'self_hosted', 'hybrid')),
    open_source text default 'unknown' check (open_source in ('yes', 'no', 'unknown')),
    api_available text default 'unknown' check (api_available in ('yes', 'no', 'unknown')),
    cli_available text default 'unknown' check (cli_available in ('yes', 'no', 'unknown')),
    mcp_available text default 'unknown' check (mcp_available in ('yes', 'no', 'unknown')),
    setup_friction text check (setup_friction in ('low', 'medium', 'high')),
    target_customer text,
    program_url text,
    program_type text,
    commission_model text,
    user_discount_available text default 'unknown' check (user_discount_available in ('yes', 'no', 'unknown')),
    last_pricing_checked date,
    last_program_checked date,
    starting_price_amount numeric,
    starting_price_currency text,
    starting_price_currency_symbol text,
    starting_price_unit text,
    starting_price_source text,
    pricing_confidence text check (pricing_confidence in ('high', 'medium', 'low')),
    pricing_notes text,
    pricing_normalized_at date,
    source_row jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index if not exists providers_category_idx on public.providers (category);
create index if not exists providers_subcategory_idx on public.providers (subcategory);
create index if not exists providers_research_status_idx on public.providers (research_status);
create index if not exists providers_updated_at_idx on public.providers (updated_at desc);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

drop trigger if exists providers_set_updated_at on public.providers;
create trigger providers_set_updated_at
before update on public.providers
for each row
execute function public.set_updated_at();

create table if not exists public.submissions (
    id uuid primary key default gen_random_uuid(),
    provider_id uuid references public.providers (id) on delete set null,
    source text not null default 'manual',
    status text not null default 'new',
    payload jsonb not null default '{}'::jsonb,
    notes text,
    created_at timestamptz not null default now()
);

create index if not exists submissions_provider_id_idx on public.submissions (provider_id);
create index if not exists submissions_created_at_idx on public.submissions (created_at desc);

create table if not exists public.click_events (
    id bigint generated by default as identity primary key,
    provider_id uuid references public.providers (id) on delete cascade,
    kind text not null default 'outbound',
    url text not null,
    referrer text,
    session_id text,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now()
);

create index if not exists click_events_provider_id_idx on public.click_events (provider_id);
create index if not exists click_events_created_at_idx on public.click_events (created_at desc);

alter table public.providers enable row level security;
alter table public.submissions enable row level security;
alter table public.click_events enable row level security;

drop policy if exists "providers are publicly readable" on public.providers;
create policy "providers are publicly readable"
on public.providers
for select
to anon, authenticated
using (true);

drop policy if exists "submissions are insertable" on public.submissions;
create policy "submissions are insertable"
on public.submissions
for insert
to anon, authenticated
with check (true);

drop policy if exists "click events are insertable" on public.click_events;
create policy "click events are insertable"
on public.click_events
for insert
to anon, authenticated
with check (true);
